### ISSUE TITLE
Workflow completes successfully, but page is not published

### ISSUE THREAD

**Issue by QuillPusher** [pranabdas/deploy-jekyll-github-action#2]
Hi, I used the workflow as-is and tried changing some parameters as well, it completes successfully, but the site is not published.
https://github.com/QuillPusher/feeling-responsive

also, you help doc says "select your source branch and path, but that defeats the reason why I am using this workflow (because [default build process is breaking](https://github.com/Phlow/feeling-responsive/issues/267#issuecomment-1784804515) ). 

<img width="1040" alt="github-deploy-select-source" src="https://github.com/pranabdas/deploy-jekyll-github-action/assets/130300172/dc126389-0307-445b-af6e-561df384bdbe">

The workflow, of course runs either way (selecting Pages>branch or selecting Pages>Github Actions), but the site is not being published to the relevant link ([https://quillpusher.github.io/feeling-responsive/](https://quillpusher.github.io/feeling-responsive/)).

What am I missing? any help would be highly appreciated

**Comment by sieb** [comment]
Take a look at https://github.com/QuillPusher/feeling-responsive/actions , your site successfully deploy.

**Comment by QuillPusher** [comment]
Yeah, I threw the kitchen sink at it, magically it worked after a few hours. 

Unable to reproduce similar results on another theme (jekyll-serif-theme) that I'm getting the same error for (I wanted to add troubleshooting documentation to these themes but my solution is not clear yet), I will keep experimenting. 

Anyway, thanks for your original guidance and sample workflow, there were some good nuggets in there
